import { computeDueOff } from "./shipping";
import type { SeedPerson, SeedTour } from "./seed";

function tour(t: SeedTour): SeedTour {
  const due = computeDueOff({
    signOn: t.signOn,
    unionHall: t.unionHall,
    assignmentType: t.assignmentType,
    siuClass: (t.seniorityClass as "A" | "B" | "C" | undefined) ?? null,
    lengthDays: t.lengthDays ?? null,
    explicitEnd: t.dueOff ?? t.signOff ?? null,
  });
  return {
    ...t,
    dueOff: due.date ?? t.dueOff,
    dueOffRule: due.rule,
  };
}

/** Current articles as of 10 Sep 2026, plus permanents on vacation. Bump when seed people/docs change. */
export const ROSTER_SEED_VERSION = 13;

export type { NseKind, NsePair } from "./nse";
export { NSE_LABELS, NSE_TRAINING, nseDocuments } from "./nse";

export const CURRENT_CREW: SeedPerson[] = [
  {
    id: "seed-kluck",
    fullName: "Christopher Eric Kluck",
    firstName: "Christopher",
    lastName: "Kluck",
    middleName: "Eric",
    ssLast4: "4112",
    dob: "1964-12-17",
    sex: "M",
    placeOfBirth: "Japan",
    citizenship: "USA",
    race: "Caucasian",
    hairColor: "Brown",
    eyeColor: "Hazel",
    height: "6'0\"",
    weight: "185",
    addressLine: "P.O. Box 1771",
    city: "Port Townsend",
    state: "WA",
    zip: "98368",
    homePhone: "360-385-0360",
    cellPhone: "360-643-1622",
    email: "chris.kluck@gmail.com",
    nearestAirport: "PAE / SEA",
    airportCode: "PAE",
    maritimeCollege: "Maine Maritime",
    yearGraduated: "1988",
    combatVeteran: false,
    maritalStatus: "Married",
    mmcNumber: "501128",
    mmcPlaceOfIssue: "NMC",
    mmcExpiration: "2027-07-30",
    passportNumber: "505519190",
    passportExpiration: "2025-01-04",
    status: "current",
    lastPosition: "MASTER",
    unionHall: "MMP",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "00",
    permanentRating: "MASTER",
    glasses: false,
    medications: "Aspirin 81mg daily; Lipitor (atorvastatin) 10mg",
    medicalRemarks: "Last dental ~2 weeks before 11 Jun 2024 packet. No glasses.",
    notes: "Permanent Master. Discharge 2 Nov 2026 (56-day). 19-page packet 11 Jun 2024 on file. Passport expired 4 Jan 2025 — renew before next foreign call. STCW medical expired 30 Jul 2025 (National through 30 Jul 2027). SASH and fam from NS5 are expired — do them this joining. 401(k) not in the packet.",
    nok: [
      {
        fullName: "Erin Kluck",
        relationship: "Wife",
        addressLine: "P.O. Box 1771",
        city: "Port Townsend",
        state: "WA",
        zip: "98368",
        cellPhone: "206-495-1389",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC — Master Unlimited", docNumber: "501128", issuedOn: "2022-07-30", expiresOn: "2027-07-30", notes: "Ref 000501128. Master, Medical PIC, First Aid. STCW Master / ECDIS / ARPA / BRM / AFF / PSC / VPDSD / GMDSS / Radar to 30 Jul 2027." },
      { docType: "passport", label: "US Passport", docNumber: "505519190", issuedOn: "2015-01-04", expiresOn: "2025-01-04", notes: "EXPIRED. POB Japan." },
      { docType: "twic", label: "TWIC", expiresOn: "2027-08-14" },
      { docType: "medical", label: "USCG Medical Certificate", issuedOn: "2022-07-30", expiresOn: "2025-07-30", notes: "STCW 30 Jul 2025 (expired) · National 30 Jul 2027. CN 3232716." },
      { docType: "drug_free", label: "Drug-free", expiresOn: "2026-12-17", notes: "From 11 Jun 2024 sign-on sheet." },
      { docType: "stcw", label: "STCW / Basic Training", expiresOn: "2027-07-30" },
      { docType: "radar", label: "Radar", expiresOn: "2027-07-30", notes: "On MMC STCW." },
      { docType: "ecdis", label: "ECDIS", expiresOn: "2027-07-30", notes: "On MMC STCW." },
      { docType: "gmdss", label: "GMDSS Operator", expiresOn: "2027-07-30", notes: "On MMC STCW." },
      { docType: "hazmat", label: "HAZMAT (49 CFR 172.704)", issuedOn: "2024-06-11", expiresOn: "2027-06-11", notes: "Rafik Shahbin, George II." },
      { docType: "sash", label: "SOCP SASH", issuedOn: "2025-06-21", expiresOn: "2026-06-21", notes: "NS5 sheet. Expired — renew this joining. Packet fam 11 Jun 2024 also signed SOCP SASH." },
      { docType: "fam", label: "Familiarization (SMM-PER-05-A1)", issuedOn: "2025-06-02", expiresOn: "2026-06-02", notes: "NS5. Packet 11 Jun 2024 on file. Expired — fam every joining." },
      { docType: "cyber", label: "Cyber awareness (SMM-SMM-08 AP3)", issuedOn: "2026-05-04", expiresOn: "2027-05-04", notes: "NS5. Packet AP3 11 Jun 2024." },
      { docType: "internet", label: "Internet Usage (SMM-SMM-08-AP4)", issuedOn: "2026-05-04", expiresOn: "2027-05-04" },
    ],
    tours: [
      tour({
        position: "MASTER",
        signOn: "2026-09-07",
        dueOff: "2026-11-02",
        signOff: undefined,
        assignmentType: "PERMANENT",
        unionHall: "MMP",
        watch: "day",
        billetCode: "00",
        notes: "Set discharge on current articles.",
      }),
    ],
    forms: [
      { formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2024-06-11" },
      { formCode: "SRO-PER-002", formLabel: "Acknowledgement / Notice of SRO Policies", completedOn: "2024-06-11" },
      { formCode: "SRO-PER-001", formLabel: "Seaman's Statement of Physical Condition", completedOn: "2024-06-11" },
      { formCode: "SMM-PER-05-A2", formLabel: "Medical Sign-On", completedOn: "2024-06-11" },
      { formCode: "SRO-PER-008", formLabel: "DOT Drug & Alcohol Release (49 CFR 40)", completedOn: "2024-06-11" },
      { formCode: "W-4", formLabel: "Federal W-4", completedOn: "2024-06-11" },
      { formCode: "I-9", formLabel: "Form I-9 Employment Eligibility", completedOn: "2024-06-11" },
      { formCode: "SRO-PAY-002", formLabel: "Direct Deposit Authorization", completedOn: "2024-06-11" },
      { formCode: "SMM-PER-05-A1", formLabel: "Familiarization Check List", completedOn: "2024-06-11" },
      { formCode: "SMM-SMM-08-A3", formLabel: "Cyber Security Training", completedOn: "2024-06-11" },
      { formCode: "SMM-SMM-08-A4", formLabel: "Internet Usage Policy", completedOn: "2024-06-11" },
      { formCode: "SASH", formLabel: "Sexual Assault / Sexual Harassment", completedOn: "2024-06-11" },
    ],
  },
  {
    id: "seed-rosca",
    fullName: "Sorin Rosca",
    firstName: "Sorin",
    lastName: "Rosca",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "C/M",
    unionHall: "MMP",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "01",
    permanentRating: "C/M",
    notes: "Permanent Chief Mate (file owner). Packet not yet scanned — add MMC / passport when convenient.",
    documents: [],
    tours: [
      tour({
        position: "C/M",
        signOn: "2026-09-01",
        assignmentType: "PERMANENT",
        unionHall: "MMP",
        watch: "day",
        billetCode: "01",
        notes: "MM&P permanent · 56-day rotation unless a discharge date is on articles.",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-mcgeough",
    fullName: "Scott McGeough",
    firstName: "Scott",
    lastName: "McGeough",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "2/M",
    unionHall: "MMP",
    assignmentType: "ROTARY",
    billetCode: "02",
    notes: "Was Chief Mate on voyage 39. Watch not printed on current articles.",
    documents: [],
    tours: [
      tour({
        position: "2/M",
        signOn: "2026-07-27",
        assignmentType: "ROTARY",
        unionHall: "MMP",
        billetCode: "02",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-hines",
    fullName: "Raymond Hines",
    firstName: "Raymond",
    lastName: "Hines",
    ssLast4: "",
    dob: "1977-05-18",
    sex: "M",
    placeOfBirth: "Albany, NY",
    citizenship: "USA",
    hairColor: "Blond",
    eyeColor: "Blue",
    height: "5'10\"",
    weight: "200",
    addressLine: "2427 2nd Ave",
    city: "Watervliet",
    state: "NY",
    zip: "12189",
    cellPhone: "518-248-8385",
    mmcNumber: "000338014",
    mmcPlaceOfIssue: "USA",
    mmcExpiration: "2028-06-13",
    passportNumber: "A86943389",
    passportExpiration: "2036-07-23",
    status: "current",
    lastPosition: "3/M",
    unionHall: "MMP",
    assignmentType: "ROTARY",
    billetCode: "03",
    notes: "MM&P 3/M dispatch 3 Aug 2026, Group C, 120 days, relieving Scott McGeough. Hall marked No Sign-on Required — ID packet only. STCW medical expired 13 Jun 2025; National medical through 13 Jun 2028.",
    documents: [
      { docType: "mmc", label: "MMC — 3rd Mate", docNumber: "000338014", issuedOn: "2023-06-13", expiresOn: "2028-06-13", notes: "Type PO. 70 in / 200 lb. Hair BLN, eyes BLU. Address 2427 2nd Ave, Watervliet NY." },
      { docType: "passport", label: "US Passport", docNumber: "A86943389", issuedOn: "2026-07-24", expiresOn: "2036-07-23" },
      { docType: "medical", label: "USCG Medical Certificate", issuedOn: "2023-06-13", expiresOn: "2025-06-13", notes: "STCW 13 Jun 2025 (expired) · National 13 Jun 2028. CN 3790914. Ref 000338014." },
      { docType: "drug_free", label: "DOT 5-panel (Quest)", issuedOn: "2026-07-29", notes: "Negative, reported 31 Jul 2026. Passport used as photo ID." },
    ],
    tours: [
      tour({
        position: "3/M",
        signOn: "2026-08-10",
        assignmentType: "ROTARY",
        unionHall: "MMP",
        dispatchRef: "3M 8.3.26",
        lengthDays: 120,
        relieving: "Scott McGeough",
        billetCode: "03",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-gonzalez-joel",
    fullName: "Joel Gonzalez",
    firstName: "Joel",
    lastName: "Gonzalez",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "BOSUN",
    unionHall: "SIU",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "04",
    permanentRating: "BOSUN",
    documents: [],
    tours: [
      tour({
        position: "BOSUN",
        signOn: "2026-07-07",
        assignmentType: "PERMANENT",
        unionHall: "SIU",
        watch: "day",
        billetCode: "04",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-guardiola",
    fullName: "Gabriel Guardiola-Berrios Jr.",
    firstName: "Gabriel",
    lastName: "Guardiola-Berrios",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "AB DAY",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "12-4",
    billetCode: "05",
    notes: "Articles 05 AB Day 12×4.",
    documents: [],
    tours: [
      tour({
        position: "AB DAY",
        signOn: "2026-06-08",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "12-4",
        billetCode: "05",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-said",
    fullName: "Zaid Said",
    firstName: "Zaid",
    lastName: "Said",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "AB DAY",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "4-8",
    billetCode: "06",
    notes: "06 AB Day 4×8.",
    documents: [],
    tours: [
      tour({
        position: "AB DAY",
        signOn: "2026-07-07",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "4-8",
        billetCode: "06",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-cooper",
    fullName: "Zaid Malik Cooper",
    firstName: "Zaid",
    lastName: "Cooper",
    middleName: "Malik",
    ssLast4: "6159",
    dob: "2000-05-21",
    sex: "M",
    placeOfBirth: "Jacksonville, FL",
    citizenship: "USA",
    hairColor: "Black",
    eyeColor: "Brown",
    height: "5'09\"",
    weight: "197",
    addressLine: "720 Celebration Ln",
    city: "Middleburg",
    state: "FL",
    zip: "32068",
    cellPhone: "904-382-7989",
    email: "zaidcooper904@yahoo.com",
    nearestAirport: "Jacksonville",
    airportCode: "JAX",
    maritimeCollege: "Paul Hall Center Marine Training",
    yearGraduated: "2020",
    maritalStatus: "Single",
    mmcNumber: "6225814",
    mmcPlaceOfIssue: "NMC Martinsburg",
    mmcExpiration: "2028-05-23",
    passportNumber: "593642437",
    passportExpiration: "2028-05-01",
    status: "current",
    lastPosition: "AB/W",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "12-4",
    billetCode: "07",
    seniorityClass: "B",
    notes: "SIU rotary AB, Class B on 86-067. Prior SRO tour Mar–May 2026.",
    nok: [
      {
        fullName: "Torri Baker",
        relationship: "Mother",
        addressLine: "1552 Elisa Dr",
        city: "Jacksonville",
        state: "FL",
        zip: "32218",
        phone: "904-233-2583",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC — AB Unlimited", docNumber: "6225814", issuedOn: "2024-09-11", expiresOn: "2028-05-23" },
      { docType: "passport", label: "US Passport", docNumber: "593642437", issuedOn: "2018-05-02", expiresOn: "2028-05-01" },
      { docType: "medical", label: "USCG Medical / STCW", expiresOn: "2028-01-28" },
      { docType: "drug_free", label: "Random exception (86-067)", expiresOn: "2026-11-11" },
    ],
    tours: [
      tour({
        position: "AB/W",
        signOn: "2026-09-01",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "12-4",
        billetCode: "07",
        seniorityClass: "B",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-garcia",
    fullName: "Mark Garcia",
    firstName: "Mark",
    lastName: "Garcia",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "AB/W",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "4-8",
    billetCode: "08",
    documents: [],
    tours: [
      tour({
        position: "AB/W",
        signOn: "2026-08-18",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "4-8",
        billetCode: "08",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-thomas",
    fullName: "Aldo Devaugh Thomas Sr.",
    firstName: "Aldo",
    lastName: "Thomas",
    middleName: "Devaugh",
    ssLast4: "4892",
    dob: "1971-12-18",
    sex: "M",
    placeOfBirth: "Jacksonville, FL",
    citizenship: "US",
    race: "Black",
    hairColor: "Black",
    eyeColor: "Brown",
    height: "5'7\"",
    weight: "193",
    addressLine: "10101 Garden Lake Ct",
    city: "Jacksonville",
    state: "FL",
    zip: "32219",
    cellPhone: "904-982-2108",
    email: "aldothomas83@gmail.com",
    nearestAirport: "Jacksonville International",
    airportCode: "JAX",
    maritalStatus: "Married",
    mmcNumber: "3877820",
    mmcPlaceOfIssue: "USA",
    mmcExpiration: "2031-08-09",
    passportNumber: "A86394669",
    passportExpiration: "2036-06-01",
    status: "current",
    lastPosition: "AB/W",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    seniorityClass: "A",
    watch: "8-12",
    billetCode: "09",
    glasses: false,
    medications: "Omeprazole 40mg (acid reflux)",
    medicalRemarks: "Left knee replacement 2020. Last dental ~6 months before sign-on, tooth removed. SIU clinic card on file.",
    notes: "ABW sign-on packet 18 Aug 2026 (24 pages). SIU Class A rotary, book T01522, dispatcher Eddie Pittman, Jacksonville. Passport and MMC taken from the credential photos and I-9, not the handwritten sign-on sheet. Direct-deposit last-4 8420 is a Navy Federal member number — SSN last-4 is 4892. 401(k) enrollment is not in this packet.",
    nok: [
      {
        fullName: "Brenda Thomas",
        relationship: "Wife",
        addressLine: "10101 Garden Lake Ct",
        city: "Jacksonville",
        state: "FL",
        zip: "32219",
        phone: "904-997-8820",
      },
    ],
    documents: [
      { docType: "mmc", label: "Merchant Mariner Credential", docNumber: "3877820", issuedOn: "2026-08-09", expiresOn: "2031-08-09", notes: "Able Seafarer-Unlimited / RFPNW / PSC / Lifeboat / Tankerman-Assistant DL / Wiper / Steward PH. STCW to 09 Aug 2031. Type PG. Height 67 in, 193 lb, hair BLK, eyes BRO." },
      { docType: "passport", label: "US Passport", docNumber: "A86394669", issuedOn: "2026-06-02", expiresOn: "2036-06-01", notes: "Data page + I-9 List A. Handwritten sign-on 6/1/2034 is wrong." },
      { docType: "twic", label: "TWIC", expiresOn: "2030-08-21" },
      { docType: "medical", label: "USCG Medical Certificate", issuedOn: "2025-02-19", expiresOn: "2027-02-19", notes: "STCW 19 Feb 2027 · National 19 Feb 2030. Exam 19 Feb 2025. Ref 3877820. Fit for duty, no limitations." },
      { docType: "drug_free", label: "Drug-free / 86-067", issuedOn: "2026-08-14", expiresOn: "2027-01-23", notes: "SIU clinic drug. 86-067 clearance 14 Aug 2026, Eddie Pittman." },
      { docType: "stcw", label: "STCW / Basic Training", expiresOn: "2031-08-09", notes: "Basic Training, VPDSD, Security Awareness, Basic Oil & Chemical Tanker, Basic IGF, PSC." },
      { docType: "hazmat", label: "HAZMAT (49 CFR 172.704)", issuedOn: "2026-08-18", expiresOn: "2029-08-18", notes: "Shipboard HAZMAT, Rafik Shahbin, George II." },
      { docType: "cyber", label: "Cyber awareness (SMM-SMM-08 AP3)", issuedOn: "2026-08-18", expiresOn: "2027-08-18", notes: "Company AP3 18 Aug 2026 plus MTSA Mod 1 certificate 15 min, Rafik Shahbin." },
      { docType: "internet", label: "Internet Usage (SMM-SMM-08-AP4)", issuedOn: "2026-08-16", expiresOn: "2027-08-16" },
      { docType: "fam", label: "Familiarization (SMM-PER-05-A1)", issuedOn: "2026-08-18", expiresOn: "2027-08-18" },
      { docType: "sash", label: "SOCP SASH", issuedOn: "2026-08-18", expiresOn: "2027-08-18", notes: "Completed SOCP SASH training signed on the familiarization checklist 18 Aug 2026. Standalone SOCP card not in this packet." },
      { docType: "other", label: "Fitness for Duty (SIU)", issuedOn: "2026-08-13", expiresOn: "2027-02-13", notes: "SHBP medical. Determination 13 Aug 2026." },
      { docType: "other", label: "Functional Capacity Exam", issuedOn: "2026-04-15", expiresOn: "2027-04-15" },
      { docType: "other", label: "Benzene Clearance", issuedOn: "2026-04-15", expiresOn: "2027-04-15" },
      { docType: "other", label: "PFT / Respirator", issuedOn: "2025-07-23", expiresOn: "2028-07-23", notes: "Unrestricted respirator use. TB screen 1 Apr 2026 negative PPD." },
    ],
    tours: [
      tour({
        position: "AB/W",
        signOn: "2026-08-18",
        port: "Jacksonville",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "8-12",
        billetCode: "09",
        seniorityClass: "A",
        dispatchRef: "T01522",
      }),
    ],
    forms: [
      { formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2026-08-18" },
      { formCode: "SRO-PER-002", formLabel: "Acknowledgement / Notice of SRO Policies", completedOn: "2026-08-18" },
      { formCode: "SRO-PER-001", formLabel: "Seaman's Statement of Physical Condition", completedOn: "2026-08-18" },
      { formCode: "SMM-PER-05-A2", formLabel: "Medical Sign-On", completedOn: "2026-08-18" },
      { formCode: "SRO-PER-008", formLabel: "DOT Drug & Alcohol Release (49 CFR 40)", completedOn: "2026-08-18" },
      { formCode: "W-4", formLabel: "Federal W-4", completedOn: "2026-08-18" },
      { formCode: "I-9", formLabel: "Form I-9 Employment Eligibility", completedOn: "2026-08-18" },
      { formCode: "SRO-PAY-002", formLabel: "Direct Deposit Authorization", completedOn: "2026-08-18" },
      { formCode: "SMM-PER-05-A1", formLabel: "Familiarization Check List", completedOn: "2026-08-18" },
      { formCode: "SMM-SMM-08-A3", formLabel: "Cyber Security Training", completedOn: "2026-08-18" },
      { formCode: "SMM-SMM-08-A4", formLabel: "Internet Usage Policy", completedOn: "2026-08-16" },
      { formCode: "SASH", formLabel: "Sexual Assault / Sexual Harassment", completedOn: "2026-08-18" },
    ],
  },
  {
    id: "seed-novak",
    fullName: "Ryan Novak",
    firstName: "Ryan",
    lastName: "Novak",
    ssLast4: "7033",
    dob: "1989-02-20",
    sex: "M",
    placeOfBirth: "Warren, MI",
    citizenship: "USA",
    race: "White",
    hairColor: "Brown",
    eyeColor: "Blue",
    height: "6'2\"",
    weight: "235",
    addressLine: "4236 Eagle Vale",
    city: "Traverse City",
    state: "MI",
    zip: "49684",
    cellPhone: "586-260-0453",
    email: "novakc89@mail.com",
    nearestAirport: "Traverse City",
    airportCode: "TVC",
    maritimeCollege: "Great Lakes Maritime",
    yearGraduated: "2013",
    combatVeteran: true,
    maritalStatus: "Married",
    mmcNumber: "2794170",
    mmcPlaceOfIssue: "USCG",
    mmcExpiration: "2025-07-29",
    passportNumber: "526270077",
    passportExpiration: "2025-05-18",
    status: "current",
    lastPosition: "C/E",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "10",
    permanentRating: "1A/E",
    notes: "Permanent 1st A/E sailing Chief Engineer covering Tesson. Credential dates from 2023 packet — confirm renewals. MMC/passport showed 2025 expiries.",
    nok: [
      {
        fullName: "Sierra Novak",
        relationship: "Wife",
        addressLine: "4236 Eagle Vale",
        city: "Traverse City",
        state: "MI",
        zip: "49684",
        phone: "810-357-5891",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC", docNumber: "2794170", expiresOn: "2025-07-29" },
      { docType: "passport", label: "US Passport", docNumber: "526270077", expiresOn: "2025-05-18" },
    ],
    tours: [
      tour({
        position: "C/E",
        signOn: "2026-09-01",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        watch: "day",
        billetCode: "10",
      }),
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2023-08-09" }],
  },
  {
    id: "seed-brown",
    fullName: "Sabrina Brown",
    firstName: "Sabrina",
    lastName: "Brown",
    ssLast4: "7574",
    dob: "1995-10-30",
    sex: "F",
    placeOfBirth: "Fairfield, CA",
    citizenship: "USA",
    race: "Latina",
    hairColor: "Brown",
    eyeColor: "Green",
    height: "5'7\"",
    weight: "145",
    addressLine: "1163 Tacia Ave",
    city: "Vacaville",
    state: "CA",
    zip: "95687",
    homePhone: "707-685-6634",
    email: "SMB1215@outlook.com",
    nearestAirport: "SMF (Sacramento, CA)",
    airportCode: "SMF",
    maritimeCollege: "CMA",
    yearGraduated: "2019",
    maritalStatus: "Single",
    mmcNumber: "5403846",
    mmcPlaceOfIssue: "USA",
    mmcExpiration: "2029-07-23",
    passportNumber: "541112441",
    passportExpiration: "2026-03-06",
    status: "current",
    lastPosition: "1A/E",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "11",
    permanentRating: "2A/E",
    notes: "Permanent watch 2 A/E sailing 1st A/E covering Jensen. Omitted from the NS5 training sheet. Signed as 2AE 2 Sep 2025 (relieving David Flynn); articles currently show 1st A/E from 1 Sep 2026.",
    nok: [
      {
        fullName: "Brian Brown",
        relationship: "Brother",
        addressLine: "1163 Tacia Ave",
        city: "Vacaville",
        state: "CA",
        zip: "95687",
        phone: "707-685-3171",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC", docNumber: "5403846", expiresOn: "2029-07-23" },
      { docType: "passport", label: "US Passport", docNumber: "541112441", expiresOn: "2026-03-06" },
    ],
    tours: [
      {
        position: "2A/E",
        signOn: "2025-09-02",
        signOff: "2026-08-31",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        relieving: "David Flynn",
        notes: "Prior permanent 2AE tour.",
      },
      tour({
        position: "1A/E",
        signOn: "2026-09-01",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        watch: "day",
        billetCode: "11",
      }),
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2025-09-02" }],
  },
  {
    id: "seed-khaleeli",
    fullName: "Cyrus E. Khaleeli",
    firstName: "Cyrus",
    lastName: "Khaleeli",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "2A/E",
    unionHall: "MEBA",
    assignmentType: "RELIEF",
    watch: "4-8",
    billetCode: "12",
    notes: "14-day relief 2 A/E watch. Set length from dispatch.",
    documents: [],
    tours: [
      tour({
        position: "2A/E",
        signOn: "2026-09-01",
        assignmentType: "RELIEF",
        unionHall: "MEBA",
        lengthDays: 14,
        watch: "4-8",
        billetCode: "12",
        notes: "George II 2nd AE W 14 day relief.",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-bawdon",
    fullName: "Ethan Bawdon",
    firstName: "Ethan",
    lastName: "Bawdon",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "3A/E",
    unionHall: "MEBA",
    assignmentType: "ROTARY",
    watch: "8-12",
    billetCode: "13",
    documents: [],
    tours: [
      tour({
        position: "3A/E",
        signOn: "2026-07-27",
        assignmentType: "ROTARY",
        unionHall: "MEBA",
        watch: "8-12",
        billetCode: "13",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-nguyen",
    fullName: "Hieu Nguyen",
    firstName: "Hieu",
    lastName: "Nguyen",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "3A/E",
    unionHall: "MEBA",
    assignmentType: "ROTARY",
    watch: "12-4",
    billetCode: "14",
    documents: [],
    tours: [
      tour({
        position: "3A/E",
        signOn: "2026-07-07",
        assignmentType: "ROTARY",
        unionHall: "MEBA",
        watch: "12-4",
        billetCode: "14",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-flynn-thomas",
    fullName: "Thomas Flynn",
    firstName: "Thomas",
    lastName: "Flynn",
    ssLast4: "",
    dob: "",
    sex: "M",
    mmcExpiration: "2029-11-04",
    passportExpiration: "2028-11-29",
    status: "current",
    lastPosition: "ELECTRICIAN",
    unionHall: "SIU",
    assignmentType: "RELIEF",
    watch: "day",
    billetCode: "15",
    notes: "Trip relief electrician covering permanent Huffman (on vacation). MMC exp 4 Nov 2029, passport 29 Nov 2028.",
    documents: [
      { docType: "mmc", label: "MMC", expiresOn: "2029-11-04" },
      { docType: "passport", label: "US Passport", expiresOn: "2028-11-29" },
    ],
    tours: [
      tour({
        position: "ELECTRICIAN",
        signOn: "2026-09-01",
        assignmentType: "RELIEF",
        unionHall: "SIU",
        watch: "day",
        billetCode: "15",
        relieving: "Richard Huffman",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-newgen",
    fullName: "Allen Newgen",
    firstName: "Allen",
    lastName: "Newgen",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "QMED",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "12-4",
    billetCode: "16",
    documents: [],
    tours: [
      tour({
        position: "QMED",
        signOn: "2026-06-23",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "12-4",
        billetCode: "16",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-hunt",
    fullName: "Dwight Hunt",
    firstName: "Dwight",
    lastName: "Hunt",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "QMED",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "4-8",
    billetCode: "17",
    notes: "Same rating on voyage 39 (signed 20 Apr 2025). Current tour from 21 Jul 2026.",
    documents: [],
    tours: [
      tour({
        position: "QMED",
        signOn: "2026-07-21",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "4-8",
        billetCode: "17",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-valdez",
    fullName: "Mike Valdez",
    firstName: "Mike",
    lastName: "Valdez",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "QMED",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "8-12",
    billetCode: "18",
    documents: [],
    tours: [
      tour({
        position: "QMED",
        signOn: "2026-06-23",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "8-12",
        billetCode: "18",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-mohseni",
    fullName: "Abdulaziz Al Mohseni",
    firstName: "Abdulaziz",
    lastName: "Al Mohseni",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "DEU",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "day",
    billetCode: "19",
    notes: "Longest current tour. SIU class not on file — due-off plans the Class A freightship latest of 75–120 days.",
    documents: [],
    tours: [
      tour({
        position: "DEU",
        signOn: "2026-05-26",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "day",
        billetCode: "19",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-huyett",
    fullName: "John F. Huyett",
    firstName: "John",
    lastName: "Huyett",
    middleName: "F.",
    ssLast4: "9162",
    dob: "1964-01-12",
    sex: "M",
    placeOfBirth: "Topeka, KS",
    citizenship: "USA",
    hairColor: "Grey",
    eyeColor: "Hazel",
    addressLine: "27809 Morningmist Dr",
    city: "Wesley Chapel",
    state: "FL",
    zip: "33543",
    cellPhone: "360-255-1986",
    email: "john.huyett45@gmail.com",
    nearestAirport: "Tampa Intl",
    airportCode: "TPA",
    maritalStatus: "Married",
    mmcNumber: "568739",
    mmcPlaceOfIssue: "USA",
    mmcExpiration: "2028-06-11",
    passportNumber: "584512100",
    passportExpiration: "2028-06-20",
    status: "current",
    lastPosition: "STEWARD",
    unionHall: "SIU",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "20",
    nok: [{ fullName: "Nadwa Huyett", relationship: "Wife", cellPhone: "360-506-7049" }],
    documents: [
      { docType: "mmc", label: "MMC", docNumber: "568739", expiresOn: "2028-06-11" },
      { docType: "passport", label: "US Passport", docNumber: "584512100", expiresOn: "2028-06-20" },
    ],
    tours: [
      tour({
        position: "STEWARD",
        signOn: "2026-06-22",
        assignmentType: "PERMANENT",
        unionHall: "SIU",
        watch: "day",
        billetCode: "20",
        port: "Wilmington",
      }),
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2026-06-22" }],
  },
  {
    id: "seed-yahia",
    fullName: "Khaled Yahia",
    firstName: "Khaled",
    lastName: "Yahia",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "COOK",
    unionHall: "SIU",
    assignmentType: "RELIEF",
    watch: "day",
    billetCode: "21",
    notes: "Trip relief cook covering permanent Kenya Scott (on vacation).",
    documents: [],
    tours: [
      tour({
        position: "COOK",
        signOn: "2026-07-27",
        assignmentType: "RELIEF",
        unionHall: "SIU",
        watch: "day",
        billetCode: "21",
        relieving: "Kenya Scott",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-sewileh",
    fullName: "Saleh Sewileh",
    firstName: "Saleh",
    lastName: "Sewileh",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "STEWARD ASSIST",
    unionHall: "SIU",
    assignmentType: "ROTARY",
    watch: "day",
    billetCode: "22",
    documents: [],
    tours: [
      tour({
        position: "STEWARD ASSIST",
        signOn: "2026-08-04",
        assignmentType: "ROTARY",
        unionHall: "SIU",
        watch: "day",
        billetCode: "22",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-walkup",
    fullName: "Philip Walkup",
    firstName: "Philip",
    lastName: "Walkup",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "2 A/E DAY",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "24",
    permanentRating: "2 A/E DAY",
    notes: "Permanent Gas 2 / 2 A/E Day on the NS5 list. HAZMAT date on that sheet is a 1990 placeholder.",
    documents: [],
    tours: [
      tour({
        position: "2 A/E DAY",
        signOn: "2026-07-21",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        watch: "day",
        billetCode: "24",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-chambers",
    fullName: "Joe Chambers",
    firstName: "Joe",
    lastName: "Chambers",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "current",
    lastPosition: "ENGINE CADET",
    unionHall: "NONE",
    assignmentType: "CADET",
    watch: "day",
    billetCode: "26",
    notes: "Engine cadet. School sets the off date — not computed.",
    documents: [],
    tours: [
      tour({
        position: "ENGINE CADET",
        signOn: "2026-07-07",
        assignmentType: "CADET",
        unionHall: "NONE",
        watch: "day",
        billetCode: "26",
      }),
    ],
    forms: [],
  },
  {
    id: "seed-shahbin",
    fullName: "Rafik Shahbin",
    firstName: "Rafik",
    lastName: "Shahbin",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "vacation",
    lastPosition: "C/M",
    unionHall: "MMP",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "01",
    permanentRating: "C/M",
    notes: "Permanent Chief Mate on vacation. Relieved by Sorin Rosca 1 Sep 2026. Packet not on file.",
    documents: [],
    tours: [],
    forms: [],
  },
  {
    id: "seed-huffman",
    fullName: "Richard Huffman",
    firstName: "Richard",
    lastName: "Huffman",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "vacation",
    lastPosition: "ELECTRICIAN",
    unionHall: "SIU",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "15",
    permanentRating: "ELECTRICIAN",
    notes: "Permanent electrician. On vacation this rotation — Flynn is trip relief covering him. Voyage 39 signed 27 May 2025.",
    documents: [],
    tours: [
      {
        position: "ELECTRICIAN",
        signOn: "2025-05-27",
        signOff: "2026-08-31",
        assignmentType: "PERMANENT",
        unionHall: "SIU",
        watch: "day",
        billetCode: "15",
      },
    ],
    forms: [],
  },
  {
    id: "seed-kenya-scott",
    fullName: "Kenya Scott",
    firstName: "Kenya",
    lastName: "Scott",
    ssLast4: "",
    dob: "",
    sex: "F",
    status: "vacation",
    lastPosition: "COOK",
    unionHall: "SIU",
    assignmentType: "PERMANENT",
    watch: "day",
    billetCode: "21",
    permanentRating: "COOK",
    notes: "Permanent cook. On vacation this rotation — Yahia is trip relief covering her. Voyage 39 signed 1 Jul 2025.",
    documents: [],
    tours: [
      {
        position: "COOK",
        signOn: "2025-07-01",
        signOff: "2026-07-26",
        assignmentType: "PERMANENT",
        unionHall: "SIU",
        watch: "day",
        billetCode: "21",
      },
    ],
    forms: [],
  },
];

export const PAST_PERMANENTS: SeedPerson[] = [
  {
    id: "seed-tesson",
    fullName: "Raymond Edward Tesson",
    firstName: "Raymond",
    lastName: "Tesson",
    middleName: "Edward",
    ssLast4: "0297",
    dob: "1975-05-20",
    sex: "M",
    placeOfBirth: "Haverhill, MA",
    citizenship: "US",
    race: "Caucasian",
    hairColor: "Brown",
    eyeColor: "Blue",
    height: "5'9\"",
    weight: "155",
    addressLine: "35 Arrowhead St",
    city: "Wellfleet",
    state: "MA",
    zip: "02667",
    homePhone: "508-214-0112",
    cellPhone: "774-454-2793",
    email: "tessonray@gmail.com",
    nearestAirport: "Logan International",
    airportCode: "BOS",
    maritimeCollege: "Massachusetts",
    yearGraduated: "1998",
    maritalStatus: "Married",
    mmcNumber: "USA000519869",
    mmcExpiration: "2024-07-05",
    passportNumber: "51912368",
    passportExpiration: "2029-04-25",
    status: "vacation",
    lastPosition: "C/E",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    notes: "Permanent Chief Engineer on the NS5 list. Off articles — Novak covering C/E. Voyage 39 signed 27 May 2025.",
    nok: [
      {
        fullName: "April E Smith Tesson",
        relationship: "Wife",
        addressLine: "35 Arrowhead St",
        city: "Wellfleet",
        state: "MA",
        zip: "02667",
        phone: "508-214-0112",
        cellPhone: "774-454-2793",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC", docNumber: "USA000519869", expiresOn: "2024-07-05" },
      { docType: "passport", label: "US Passport", docNumber: "51912368", expiresOn: "2029-04-25" },
    ],
    tours: [
      {
        position: "C/E",
        signOn: "2025-05-27",
        signOff: "2026-08-31",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        watch: "day",
        billetCode: "10",
      },
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2023-09-19" }],
  },
  {
    id: "seed-jensen",
    fullName: "Austin D. Jensen",
    firstName: "Austin",
    lastName: "Jensen",
    middleName: "D.",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "vacation",
    lastPosition: "1A/E",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    notes: "Permanent 1st A/E on the NS5 list. Off articles. MEBA dispatch 1st Assist Eng Unlimited 16 Apr 2024, relieving Matthew Jernigan.",
    documents: [],
    tours: [
      {
        position: "1A/E",
        signOn: "2024-04-16",
        signOff: "2026-08-31",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        relieving: "Matthew Jernigan",
        dispatchRef: "JENA0215",
        watch: "day",
        billetCode: "11",
      },
    ],
    forms: [],
  },
  {
    id: "seed-tuck",
    fullName: "Joe Mark Tuck",
    firstName: "Joe",
    lastName: "Tuck",
    middleName: "Mark",
    ssLast4: "6259",
    dob: "1955-07-29",
    sex: "M",
    placeOfBirth: "Seymour, Texas",
    citizenship: "USA",
    race: "Caucasian",
    hairColor: "Grey",
    eyeColor: "Brown",
    height: "6'02\"",
    weight: "180",
    addressLine: "1189 Waimanu St apt 2403",
    city: "Honolulu",
    state: "HI",
    zip: "96814",
    homePhone: "352-281-7177",
    email: "jmarktuck@gmail.com",
    nearestAirport: "Daniel K. Inouye, Honolulu International",
    airportCode: "HNL",
    maritimeCollege: "Tx A&M",
    yearGraduated: "1979",
    maritalStatus: "Married, but withhold at higher Single rate",
    mmcNumber: "443357",
    mmcPlaceOfIssue: "Martinsburg WV",
    mmcExpiration: "2026-11-10",
    passportNumber: "587184920",
    passportExpiration: "2028-03-14",
    status: "vacation",
    lastPosition: "MASTER",
    unionHall: "MMP",
    assignmentType: "PERMANENT",
    notes: "Permanent Master on the NS5 list. Packet on file (Long Beach 2 Apr 2024). Kluck is on the current articles.",
    nok: [
      {
        fullName: "Colleen Akimi Tuck",
        relationship: "Wife",
        addressLine: "1189 Waimanu St apt 2403",
        city: "Honolulu",
        state: "HI",
        zip: "96814",
        phone: "352-562-1361",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC — Master", docNumber: "443357", expiresOn: "2026-11-10" },
      { docType: "passport", label: "US Passport", docNumber: "587184920", expiresOn: "2028-03-14" },
    ],
    tours: [
      {
        position: "MASTER",
        signOn: "2024-04-02",
        signOff: "2026-09-06",
        port: "Long Beach",
        assignmentType: "PERMANENT",
        unionHall: "MMP",
        watch: "day",
        billetCode: "00",
      },
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2024-04-02" }],
  },
  {
    id: "seed-gupta",
    fullName: "Sanjay Gupta",
    firstName: "Sanjay",
    lastName: "Gupta",
    ssLast4: "7665",
    dob: "1967-05-20",
    sex: "M",
    placeOfBirth: "Cochin, Kerala, India",
    citizenship: "U.S.",
    race: "Indian",
    hairColor: "Black",
    eyeColor: "Brown",
    height: "5'7\"",
    weight: "205",
    addressLine: "4707 79th Ave Ct W",
    city: "University Place",
    state: "WA",
    zip: "98466",
    homePhone: "253-566-5949",
    cellPhone: "253-359-4388",
    email: "sanjay123gupta3@gmail.com",
    nearestAirport: "SEATAC",
    maritalStatus: "Married",
    mmcNumber: "1678973",
    mmcExpiration: "2026-05-07",
    passportNumber: "567967506",
    passportExpiration: "2031-04-22",
    status: "vacation",
    lastPosition: "BOSUN",
    unionHall: "SIU",
    assignmentType: "PERMANENT",
    nok: [
      {
        fullName: "Deepali Sahu",
        relationship: "Wife",
        addressLine: "4707 79th Ave Ct W",
        city: "University Place",
        state: "WA",
        zip: "98466",
        phone: "253-292-7784",
        cellPhone: "253-292-7784",
      },
    ],
    documents: [
      { docType: "mmc", label: "MMC", docNumber: "1678973", expiresOn: "2026-05-07" },
      { docType: "passport", label: "US Passport", docNumber: "567967506", expiresOn: "2031-04-22" },
    ],
    tours: [
      {
        position: "BOSUN",
        signOn: "2026-03-03",
        signOff: "2026-07-06",
        port: "LA",
        assignmentType: "PERMANENT",
        unionHall: "SIU",
        watch: "day",
        billetCode: "04",
      },
    ],
    forms: [{ formCode: "SRO-PER-003", formLabel: "Sign on Information", completedOn: "2026-03-03" }],
  },
  {
    id: "seed-albrecht",
    fullName: "Edward F. Albrecht",
    firstName: "Edward",
    lastName: "Albrecht",
    middleName: "F.",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "vacation",
    lastPosition: "2 A/E DAY",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    notes: "Permanent Gas 2 on the NS5 list. Off articles — Walkup covering 2 A/E Day. Medical sign-off 13 May 2024 as 2AE, no accident/illness.",
    documents: [],
    tours: [
      {
        position: "2 A/E DAY",
        signOn: "2025-05-27",
        signOff: "2026-07-20",
        assignmentType: "PERMANENT",
        unionHall: "MEBA",
        watch: "day",
        billetCode: "24",
      },
    ],
    forms: [{ formCode: "SMM-PER-05-A3", formLabel: "Medical Sign-Off", completedOn: "2024-05-13" }],
  },
  {
    id: "seed-navarrete",
    fullName: "Navarrete",
    firstName: "",
    lastName: "Navarrete",
    ssLast4: "",
    dob: "",
    sex: "M",
    status: "vacation",
    lastPosition: "C/E",
    unionHall: "MEBA",
    assignmentType: "PERMANENT",
    notes: "Permanent Chief Engineer on the NS5 training list. First name not on that sheet. Packet not on file. All five NSE tickets on the sheet are expired.",
    documents: [],
    tours: [],
    forms: [],
  },
];
