import type { SignOnRequirement } from "./types";

/** Controlled sign-on list from SRO packets + SMM-PER (the live SMS crewing book). */
export const DEFAULT_REQUIREMENTS: Omit<SignOnRequirement, "id">[] = [
  { code: "SRO-PER-003", label: "Sign on Information", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 10, notes: "Personal, MMC, passport, next of kin." },
  { code: "SRO-PER-002", label: "Acknowledgement / Notice of SRO Policies", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 20, notes: "Drugs, alcohol, contraband, rest hours, PPE, harassment." },
  { code: "SRO-PER-001", label: "Seaman's Statement of Physical Condition", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 30, notes: null },
  { code: "SMM-PER-05-A2", label: "Medical Sign-On", kind: "form", appliesTo: "all", required: true, source: "sms", sortOrder: 40, notes: "Medications, allergies, eyeglasses." },
  { code: "SRO-PER-008", label: "DOT Drug & Alcohol Release (49 CFR 40)", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 50, notes: null },
  { code: "W-4", label: "Federal W-4", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 60, notes: null },
  { code: "I-9", label: "Form I-9 Employment Eligibility", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 70, notes: null },
  { code: "SRO-PAY-002", label: "Direct Deposit Authorization", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 80, notes: "Do not store account numbers in this ledger." },
  { code: "401K", label: "401(k) enrollment or opt-out", kind: "form", appliesTo: "all", required: true, source: "sro", sortOrder: 90, notes: "MM&P / union plan as applicable." },
  { code: "SMM-SMM-08-A3", label: "Cyber Security Training", kind: "form", appliesTo: "all", required: true, source: "sms", sortOrder: 100, notes: null },
  { code: "SMM-SMM-08-A4", label: "Internet Usage Policy", kind: "form", appliesTo: "all", required: true, source: "sms", sortOrder: 110, notes: null },
  { code: "SMM-PER-05-A1", label: "Familiarization Check List", kind: "form", appliesTo: "all", required: true, source: "sms", sortOrder: 120, notes: "ISM 6.3 / STCW A-VI/1. Complete before assigned duties." },
  { code: "SASH", label: "Sexual Assault / Sexual Harassment", kind: "certificate", appliesTo: "all", required: true, source: "sms", sortOrder: 130, notes: "SOCP SASH / SVO-SMM-03. 1-year validity on the NS5 sheet." },
  { code: "FAM", label: "Familiarization (SMM-PER-05-AP1)", kind: "certificate", appliesTo: "all", required: true, source: "sms", sortOrder: 140, notes: "1-year validity. NSE training list." },
  { code: "CYBER", label: "Cyber awareness (SMM-SMM-08 Mod 1 / AP3)", kind: "certificate", appliesTo: "all", required: true, source: "sms", sortOrder: 150, notes: "1-year. NSE tracks the three 101.650 modules separately; AP3 is the company form." },
  { code: "INTERNET", label: "Internet Usage (SMM-SMM-08-AP4)", kind: "certificate", appliesTo: "all", required: true, source: "sms", sortOrder: 160, notes: "1-year validity. NSE training list." },
  { code: "HAZMAT", label: "HAZMAT (SMM-PER-06 / 49 CFR 172.704)", kind: "certificate", appliesTo: "deck_officer", required: true, source: "sms", sortOrder: 170, notes: "H = 1 per vessel if carrying HAZMAT. Deck officers. 3-year HMR recurrent. Not SMM-OPS-11 (cargo ops)." },
  { code: "MMC", label: "Merchant Mariner Credential", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 200, notes: null },
  { code: "PASSPORT", label: "Passport", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 210, notes: null },
  { code: "TWIC", label: "TWIC", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 220, notes: null },
  { code: "STCW", label: "STCW / Basic Training", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 230, notes: null },
  { code: "MEDICAL", label: "Medical Certificate (CG-719K)", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 240, notes: null },
  { code: "DRUG_FREE", label: "Drug-Free / chemical test", kind: "certificate", appliesTo: "all", required: true, source: "uscg", sortOrder: 250, notes: "Must be current at sign-on." },
  { code: "RADAR", label: "Radar / ARPA", kind: "certificate", appliesTo: "deck_officer", required: true, source: "uscg", sortOrder: 300, notes: null },
  { code: "ECDIS", label: "ECDIS", kind: "certificate", appliesTo: "deck_officer", required: true, source: "uscg", sortOrder: 310, notes: null },
  { code: "GMDSS", label: "GMDSS Operator", kind: "certificate", appliesTo: "deck_officer", required: true, source: "uscg", sortOrder: 320, notes: null },
  { code: "VSO", label: "Vessel Security Officer", kind: "certificate", appliesTo: "deck_officer", required: false, source: "uscg", sortOrder: 330, notes: "Required if designated VSO." },
];

export const DOC_TYPE_TO_REQ: Record<string, string> = {
  mmc: "MMC",
  passport: "PASSPORT",
  twic: "TWIC",
  stcw: "STCW",
  bst: "STCW",
  medical: "MEDICAL",
  drug_free: "DRUG_FREE",
  radar: "RADAR",
  ecdis: "ECDIS",
  gmdss: "GMDSS",
  vso: "VSO",
  sash: "SASH",
  cyber: "CYBER",
  cyber_ot: "CYBER",
  cyber_key: "CYBER",
  fam: "FAM",
  internet: "INTERNET",
  hazmat: "HAZMAT",
};

export const FORM_CODE_ALIASES: Record<string, string> = {
  "SRO-PER-003": "SRO-PER-003",
  "SIGN ON INFORMATION": "SRO-PER-003",
  "SRO-PER-002": "SRO-PER-002",
  "ACKNOWLEDGEMENT": "SRO-PER-002",
  "NOTICE OF SRO POLICIES": "SRO-PER-002",
  "SRO-PER-001": "SRO-PER-001",
  "STATEMENT OF PHYSICAL CONDITION": "SRO-PER-001",
  "SMM-PER-05-A2": "SMM-PER-05-A2",
  "MEDICAL SIGN-ON": "SMM-PER-05-A2",
  "MEDICAL SIGN ON": "SMM-PER-05-A2",
  "SRO-PER-008": "SRO-PER-008",
  "49 CFR": "SRO-PER-008",
  "DRUG AND ALCOHOL": "SRO-PER-008",
  "W-4": "W-4",
  "W4": "W-4",
  "I-9": "I-9",
  I9: "I-9",
  "SRO-PAY-002": "SRO-PAY-002",
  "DIRECT DEPOSIT": "SRO-PAY-002",
  "401K": "401K",
  "401(K)": "401K",
  "OPT-OUT": "401K",
  "SMM-SMM-08-A3": "SMM-SMM-08-A3",
  "CYBER SECURITY TRAINING": "SMM-SMM-08-A3",
  "SMM-SMM-08-A4": "SMM-SMM-08-A4",
  "INTERNET USAGE": "SMM-SMM-08-A4",
  "SMM-PER-05-A1": "SMM-PER-05-A1",
  FAMILIARIZATION: "SMM-PER-05-A1",
  SASH: "SASH",
  "SEXUAL ASSAULT": "SASH",
  "SEXUAL HARASSMENT": "SASH",
  "SVO-SMM-03": "SASH",
  FAM: "FAM",
  "SMM-PER-05-AP1": "FAM",
  CYBER: "CYBER",
  "SMM-SMM-08-AP3": "CYBER",
  INTERNET: "INTERNET",
  "SMM-SMM-08": "INTERNET",
  HAZMAT: "HAZMAT",
  "SMM-OPS-11": "HAZMAT",
};
