/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CyberRouteImport } from './routes/cyber'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as HazmatRouteImport } from './routes/hazmat'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PermanentsRouteImport } from './routes/permanents'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as SignOnRouteImport } from './routes/sign-on'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as CrewIndexRouteImport } from './routes/crew.index'
import { Route as CrewCrewIdRouteImport } from './routes/crew.$crewId'
import { Route as CrewPrintRouteImport } from './routes/crew.print'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberRoute = CyberRouteImport.update({
  id: '/cyber',
  path: '/cyber',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const HazmatRoute = HazmatRouteImport.update({
  id: '/hazmat',
  path: '/hazmat',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PermanentsRoute = PermanentsRouteImport.update({
  id: '/permanents',
  path: '/permanents',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOnRoute = SignOnRouteImport.update({
  id: '/sign-on',
  path: '/sign-on',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewCrewIdRoute = CrewCrewIdRouteImport.update({
  id: '/crew/$crewId',
  path: '/crew/$crewId',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewPrintRoute = CrewPrintRouteImport.update({
  id: '/crew/print',
  path: '/crew/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/expiry': typeof ExpiryRoute
  '/hazmat': typeof HazmatRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/permanents': typeof PermanentsRoute
  '/requirements': typeof RequirementsRoute
  '/sign-on': typeof SignOnRoute
  '/training': typeof TrainingRoute
  '/crew/$crewId': typeof CrewCrewIdRoute
  '/crew/print': typeof CrewPrintRoute
  '/crew/': typeof CrewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/expiry': typeof ExpiryRoute
  '/hazmat': typeof HazmatRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/permanents': typeof PermanentsRoute
  '/requirements': typeof RequirementsRoute
  '/sign-on': typeof SignOnRoute
  '/training': typeof TrainingRoute
  '/crew/$crewId': typeof CrewCrewIdRoute
  '/crew/print': typeof CrewPrintRoute
  '/crew': typeof CrewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/expiry': typeof ExpiryRoute
  '/hazmat': typeof HazmatRoute
  '/ingest': typeof IngestRoute
  '/login': typeof LoginRoute
  '/permanents': typeof PermanentsRoute
  '/requirements': typeof RequirementsRoute
  '/sign-on': typeof SignOnRoute
  '/training': typeof TrainingRoute
  '/crew/$crewId': typeof CrewCrewIdRoute
  '/crew/print': typeof CrewPrintRoute
  '/crew/': typeof CrewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cyber'
    | '/expiry'
    | '/hazmat'
    | '/ingest'
    | '/login'
    | '/permanents'
    | '/requirements'
    | '/sign-on'
    | '/training'
    | '/crew/$crewId'
    | '/crew/print'
    | '/crew/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cyber'
    | '/expiry'
    | '/hazmat'
    | '/ingest'
    | '/login'
    | '/permanents'
    | '/requirements'
    | '/sign-on'
    | '/training'
    | '/crew/$crewId'
    | '/crew/print'
    | '/crew'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cyber'
    | '/expiry'
    | '/hazmat'
    | '/ingest'
    | '/login'
    | '/permanents'
    | '/requirements'
    | '/sign-on'
    | '/training'
    | '/crew/$crewId'
    | '/crew/print'
    | '/crew/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyberRoute: typeof CyberRoute
  ExpiryRoute: typeof ExpiryRoute
  HazmatRoute: typeof HazmatRoute
  IngestRoute: typeof IngestRoute
  LoginRoute: typeof LoginRoute
  PermanentsRoute: typeof PermanentsRoute
  RequirementsRoute: typeof RequirementsRoute
  SignOnRoute: typeof SignOnRoute
  TrainingRoute: typeof TrainingRoute
  CrewCrewIdRoute: typeof CrewCrewIdRoute
  CrewPrintRoute: typeof CrewPrintRoute
  CrewIndexRoute: typeof CrewIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber': {
      id: '/cyber'
      path: '/cyber'
      fullPath: '/cyber'
      preLoaderRoute: typeof CyberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazmat': {
      id: '/hazmat'
      path: '/hazmat'
      fullPath: '/hazmat'
      preLoaderRoute: typeof HazmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permanents': {
      id: '/permanents'
      path: '/permanents'
      fullPath: '/permanents'
      preLoaderRoute: typeof PermanentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-on': {
      id: '/sign-on'
      path: '/sign-on'
      fullPath: '/sign-on'
      preLoaderRoute: typeof SignOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/$crewId': {
      id: '/crew/$crewId'
      path: '/crew/$crewId'
      fullPath: '/crew/$crewId'
      preLoaderRoute: typeof CrewCrewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/print': {
      id: '/crew/print'
      path: '/crew/print'
      fullPath: '/crew/print'
      preLoaderRoute: typeof CrewPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyberRoute: CyberRoute,
  ExpiryRoute: ExpiryRoute,
  HazmatRoute: HazmatRoute,
  IngestRoute: IngestRoute,
  LoginRoute: LoginRoute,
  PermanentsRoute: PermanentsRoute,
  RequirementsRoute: RequirementsRoute,
  SignOnRoute: SignOnRoute,
  TrainingRoute: TrainingRoute,
  CrewCrewIdRoute: CrewCrewIdRoute,
  CrewPrintRoute: CrewPrintRoute,
  CrewIndexRoute: CrewIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
